add support for shape files with non us-ascii filenames.

diff --git a/test_encoding_utf8 b/test_encoding_utf8
--- a/test_encoding_utf8
+++ b/test_encoding_utf8
@@ -74,8 +74,42 @@ filenamebase=test_encoding_fileαβγ
     errorcount=`expr $errorcount + 1`
   fi
 
+# test input file name mangling with shape files
+  echo "testing input file name with shape files"
+  rm -f ${TMPDIR}/test_encoding_file*
+  for ext in cpg dbf prj shp shx
+  do
+    cp ${REFERENCE}/gis.osm_railways_free_1.${ext} ${TMPDIR}/${filenamebase}.${ext}
+  done
+  ${PNAME} -r -i shape -f ${TMPDIR}/${filenamebase}.shp -o kml -F ${TMPDIR}/test_encoding_fileo.kml || {
+    echo "ERROR: The input file name was mangled."
+    errorcount=`expr $errorcount + 1`
+  }
+
+# test output file name mangling with shape files
+  echo "testing output file name with shape files"
+  rm -f ${TMPDIR}/test_encoding_file*
+  ${PNAME} -r -i gpx -f ${REFERENCE}/bounds-test.gpx -o shape -F ${TMPDIR}/${filenamebase}.shp
+  for ext in cpg dbf shp shx
+  do
+    count=$(ls -1 -l ${TMPDIR}/${filenamebase}.${ext} 2>/dev/null | wc -l)
+    if [ $count -lt 1 ]; then
+      echo "ERROR: The output file name was mangled."
+      errorcount=`expr $errorcount + 1`
+    fi
+  done
+  rm -f ${TMPDIR}/test_encoding_file*
+  ${PNAME} -w -i gpx -f ${REFERENCE}/bounds-test.gpx -o shape -F ${TMPDIR}/${filenamebase}.shp
+  for ext in cpg dbf shp shx
+  do
+    count=$(ls -1 -l ${TMPDIR}/${filenamebase}.${ext} 2>/dev/null | wc -l)
+    if [ $count -lt 1 ]; then
+      echo "ERROR: The output file name was mangled."
+      errorcount=`expr $errorcount + 1`
+    fi
+  done
+
 # TODO: add tests to cover formats that use other open methods.
-#       for example shape files.
 
 else
   echo "$0 cannot run without the UTF-8 charmap."
