Revert "test_encoding refinements"
This reverts commit dac5492ff21a1c6d341d3d16ad49d340aa2a9f27.

diff --git a/test_encoding b/test_encoding
--- a/test_encoding
+++ b/test_encoding
@@ -15,28 +15,27 @@ if  locale -a | grep -q en_US.iso88591 ; then
   export LC_ALL=en_US.iso88591
   rm -f ${TMPDIR}/file*.kml
   rm -f ${TMPDIR}/file*.gpx
-  rm -f ${TMPDIR}/file*.csv
 
 # test input file name mangling
-  cp ${REFERENCE}/bounds-test.gpx ${TMPDIR}/fileÂ¢.gpx
-  ${PNAME} -i gpx -f ${TMPDIR}/fileÂ¢.gpx -o kml -F ${TMPDIR}/fileo.kml || {
-    echo "ERROR: The GPX input file name was mangled."
+  cp ${REFERENCE}/bounds-test.gpx ${TMPDIR}/file¢.gpx
+  ${PNAME} -i gpx -f ${TMPDIR}/file¢.gpx -o kml -F ${TMPDIR}/fileo.kml || {
+    echo "ERROR: The input file name was mangled."
     errorcount=`expr $errorcount + 1`
   }
 
 # test output file name mangling
-  ${PNAME} -i gpx -f ${REFERENCE}/bounds-test.gpx -o kml -F ${TMPDIR}/fileÂ¢.kml
-  count=$(ls -1 -l ${TMPDIR}/fileÂ¢.kml | wc -l)
+  ${PNAME} -i gpx -f ${REFERENCE}/bounds-test.gpx -o kml -F ${TMPDIR}/file¢.kml
+  count=$(ls -1 -l ${TMPDIR}/file¢.kml | wc -l)
   if [ $count -lt 1 ]; then
-    echo "ERROR: The KML output file name was mangled."
+    echo "ERROR: The output file name was mangled."
     errorcount=`expr $errorcount + 1`
   fi
 
 # test output file name mangling using a format that uses gbfile
-  ${PNAME} -i gpx -f ${REFERENCE}/bounds-test.gpx -o unicsv -F ${TMPDIR}/fileÂ¢.csv
-  count=$(ls -1 -l ${TMPDIR}/fileÂ¢.csv | wc -l)
+  ${PNAME} -i gpx -f ${REFERENCE}/bounds-test.gpx -o unicsv -F ${TMPDIR}/file¢.csv
+  count=$(ls -1 -l ${TMPDIR}/file¢.csv | wc -l)
   if [ $count -lt 1 ]; then
-    echo "ERROR: The CSV output file name was mangled."
+    echo "ERROR: The output file name was mangled."
     errorcount=`expr $errorcount + 1`
   fi
 else
