make resigning condtional, xcode 26.1

diff --git a/gui/package_app b/gui/package_app
--- a/gui/package_app
+++ b/gui/package_app
@@ -137,12 +137,14 @@ else # Mac
   set -x
   "${MACDEPLOYQT}" "${APPBUNDLE}" -executable="${APPBUNDLE}/Contents/MacOS/gpsbabel" -verbose=2 "${CODESIGN}"
   if [ ! -z "${CODESIGN}" ]; then
-    # GPSBabelFE ends not being signed due incorrect signing order of gpsbabel in macdeployqt.
-    # but QtCore5Compat and gpsbabel are signed belatedly.
-    echo "Re-signing GPSBabelFE assuming macdeployqt failed to sign it"
-    # the options we use to resign are the same as macdeployqt defaults (no hardened runtime, timestamps, extra enttilements)
-    codesign --preserve-metadata=identifier,entitlements --force -s - "${APPBUNDLE}/Contents/MacOS/GPSBabelFE"
-    codesign --deep --verify --verbose=2 "${APPBUNDLE}"
+    if ! codesign --deep --verify "${APPBUNDLE}"; then
+      # GPSBabelFE ends not being signed due incorrect signing order of gpsbabel in macdeployqt.
+      # but QtCore5Compat and gpsbabel are signed belatedly.
+      echo "Re-signing GPSBabelFE assuming macdeployqt failed to sign it"
+      # the options we use to resign are the same as macdeployqt defaults (no hardened runtime, timestamps, extra enttilements)
+      codesign --preserve-metadata=identifier,entitlements --force -s - "${APPBUNDLE}/Contents/MacOS/GPSBabelFE"
+      codesign --deep --verify --verbose=2 "${APPBUNDLE}"
+    fi
   fi
   # because we might have had to fix codesigning we have to create the dmg instead of letting macdeployqt do it.
   hdiutil create "${DMG}" -srcfolder "${APPBUNDLE}" -format UDZO -fs APFS -volname "${VOLNAME}"
