Add a shortname test.

diff --git a/gpsbabel/testo b/gpsbabel/testo
--- a/gpsbabel/testo
+++ b/gpsbabel/testo
@@ -346,3 +346,22 @@ ${PNAME} -i xmap -f reference/arcdist_input.txt \
          -o xmap -F ${TMPDIR}/polygon.txt
 compare ${TMPDIR}/polygon.txt reference/polygon_output.txt
 
+
+
+
+#
+# This is  nasty.   If we have a dictionary handy, treat it as a list of
+# waypoints and reduce all the names to eight characters.   Fewer chars
+# results in lost waypoints currently and that's a defect.
+#
+DICT=/usr/share/dict/words
+if [ -f $DICT ]; 
+then
+	WORDS=`cat $DICT | wc -l`
+	SWORDS=`${PNAME} -i gpsdrive -f $DICT -o gpsdrive,snlen=8 -F /dev/fd/1 | wc -l`
+	if [ $WORDS -ne $SWORDS ];
+	then
+		echo "Shortname reduction failed."
+		exit 1	
+	fi
+fi
