qt installer improvements
validate installs
add debug for failed installs

diff --git a/tools/travis_install_linux_coverage b/tools/travis_install_linux_coverage
--- a/tools/travis_install_linux_coverage
+++ b/tools/travis_install_linux_coverage
@@ -1,24 +1,53 @@
 #!/bin/bash -ex
 #
 # This script is run on travis for the install stage of mac builds.
-# Note the script must be sourced if you want the modified PATH to
-# be used outside this script.
 #
 
+#debug failed install
+function debug() {
+  cat ${CACHEDIR}/qt-${QT_VERSION}.env
+  find ${CACHEDIR}/Qt -maxdepth 3 -ls
+  cat ${CACHEDIR}/Qt/InstallationLog.txt
+  cat ${CACHEDIR}/Qt/components.xml
+  echo "$1" >&2
+  exit 1
+}
+
+# validate install
+function validate() {
+  (
+    set +e
+    source ${CACHEDIR}/qt-${QT_VERSION}.env
+    if [ "$(qmake -query QT_INSTALL_BINS)" != "${QTDIR}/bin" ]; then
+      debug "ERROR: unexpected Qt location."
+    fi
+    if [ "$(qmake -query QT_VERSION)" != "${QT_VERSION}" ]; then
+      debug "ERROR: wrong Qt version."
+    fi
+  )
+}
+
+QT_VERSION=${1:-5.7.1}
+QT_VERSION_SHORT=${QT_VERSION//./}
+# older Qt releases use different package names and install locations.
+QT_VERSION_XY=$(echo ${QT_VERSION} | cut -d "." -f -2)
+QT_VERSION_XY_SHORT=${QT_VERSION_XY//./}
+
 # our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
-QTDIR=${HOME}/Qt/5.7/gcc_64
+CACHEDIR=${HOME}/Cache
+QTDIR=${CACHEDIR}/Qt/${QT_VERSION_XY}/gcc_64
 
 if [ -d "${QTDIR}/bin" ]; then
   echo "Using cached Qt."
   echo "If you need to clear the cache see"
   echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
 else
-  pushd ${HOME};
-  rm -fr Qt
-  # install_qt creates the install at $PWD/Qt.
-  QT_CI_PACKAGES=qt.57.gcc_64 PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt 5.7.1
-  popd;
+  rm -fr ${CACHEDIR}
+  mkdir -p ${CACHEDIR}
+  pushd ${CACHEDIR}
+  # install-qt creates the install at $PWD/Qt.
+  QT_CI_PACKAGES=qt.${QT_VERSION_XY_SHORT}.gcc_64 QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
+  popd
+  validate
+  rm ${CACHEDIR}/qt-opensource*.run
 fi
-# note that qt-5.7.1.env created by install-qt is not cached!
-export PATH=${QTDIR}/bin:${PATH}
-unset -v QTDIR
diff --git a/tools/travis_install_linux_local b/tools/travis_install_linux_local
--- a/tools/travis_install_linux_local
+++ b/tools/travis_install_linux_local
@@ -3,8 +3,32 @@
 # This script is run on travis for the install stage of mac builds.
 #
 
+#debug failed install
+function debug() {
+  cat ${CACHEDIR}/qt-${QT_VERSION}.env
+  find ${CACHEDIR}/Qt -maxdepth 3 -ls
+  cat ${CACHEDIR}/Qt/InstallationLog.txt
+  cat ${CACHEDIR}/Qt/components.xml
+  echo "$1" >&2
+  exit 1
+}
+
+# validate install
+function validate() {
+  (
+    set +e
+    source ${CACHEDIR}/qt-${QT_VERSION}.env
+    if [ "$(qmake -query QT_INSTALL_BINS)" != "${QTDIR}/bin" ]; then
+      debug "ERROR: unexpected Qt location."
+    fi
+    if [ "$(qmake -query QT_VERSION)" != "${QT_VERSION}" ]; then
+      debug "ERROR: wrong Qt version."
+    fi
+  )
+}
+
 QT_VERSION=${1:-5.12.0}
-QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')
+QT_VERSION_SHORT=${QT_VERSION//./}
 
 # our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
 CACHEDIR=${HOME}/Cache
@@ -20,15 +44,9 @@ else
   pushd ${CACHEDIR}
   # install-qt creates the install at $PWD/Qt.
   QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.gcc_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
-  popd;
-  if [ ! -e ${QTDIR}/bin/qmake ]; then
-    echo "ERROR: qmake not found on the installation path." >&2
-    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
-    find ${CACHEDIR}/Qt -maxdepth 3
-    cat ${CACHEDIR}/Qt/InstallationLog.txt
-    cat ${CACHEDIR}/Qt/components.xml
-    exit 1
-  fi
+  popd
+  validate
+  rm ${CACHEDIR}/qt-opensource*.run
 fi
 
 # prepare locale for test_encoding_latin1, requires locales package.
diff --git a/tools/travis_install_osx b/tools/travis_install_osx
--- a/tools/travis_install_osx
+++ b/tools/travis_install_osx
@@ -3,10 +3,34 @@
 # This script is run on travis for the install stage of mac builds.
 #
 
-QT_VERSION=${1:-5.12.0}
-QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')
+#debug failed install
+function debug() {
+  cat ${CACHEDIR}/qt-${QT_VERSION}.env
+  find ${CACHEDIR}/Qt -maxdepth 3 -ls
+  cat ${CACHEDIR}/Qt/InstallationLog.txt
+  cat ${CACHEDIR}/Qt/components.xml
+  echo "$1" >&2
+  exit 1
+}
 
-# our expectation is that install-qt-osx creates $QTDIR, $QTDIR/bin.
+# validate install
+function validate() {
+  (
+    set +e
+    source ${CACHEDIR}/qt-${QT_VERSION}.env
+    if [ "$(qmake -query QT_INSTALL_BINS)" != "${QTDIR}/bin" ]; then
+      debug "ERROR: unexpected Qt location."
+    fi
+    if [ "$(qmake -query QT_VERSION)" != "${QT_VERSION}" ]; then
+      debug "ERROR: wrong Qt version."
+    fi
+  )
+}
+
+QT_VERSION=${1:-5.12.0}
+QT_VERSION_SHORT=${QT_VERSION//./}
+
+# our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
 CACHEDIR=${HOME}/Cache
 QTDIR=${CACHEDIR}/Qt/${QT_VERSION}/clang_64
 
@@ -18,15 +42,9 @@ else
   rm -fr ${CACHEDIR}
   mkdir -p ${CACHEDIR}
   pushd ${CACHEDIR}
-  # install-qt-osx creates the install at $PWD/Qt.
-  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.clang_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt-osx ${QT_VERSION}
-  popd;
-  if [ ! -e ${QTDIR}/bin/qmake ]; then
-    echo "ERROR: qmake not found on the installation path." >&2
-    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
-    find ${CACHEDIR}/Qt -maxdepth 3
-    cat ${CACHEDIR}/Qt/InstallationLog.txt
-    cat ${CACHEDIR}/Qt/components.xml
-    exit 1
-  fi
+  # install-qt creates the install at $PWD/Qt.
+  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.clang_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
+  popd
+  validate
+  rm ${CACHEDIR}/qt-opensource*.dmg
 fi
