add generic qt installer for osx.
add travis builds with osx and qt 5.9.7, 5.12.0
update qtci extract-qt-installer from upstream.
add some error detection and debug to travis_install_osx, travis_intall_linux_local.

diff --git a/tools/travis_install_linux_local b/tools/travis_install_linux_local
--- a/tools/travis_install_linux_local
+++ b/tools/travis_install_linux_local
@@ -5,8 +5,11 @@
 # be used outside this script.
 #
 
+QT_VERSION=${1:-5.12.0}
+QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')
+
 # our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
-QTDIR=${HOME}/Qt/5.9.7/gcc_64
+QTDIR=${HOME}/Qt/${QT_VERSION}/gcc_64
 
 if [ -d "${QTDIR}/bin" ]; then
   echo "Using cached Qt."
@@ -15,13 +18,21 @@ if [ -d "${QTDIR}/bin" ]; then
 else
   pushd ${HOME};
   rm -fr Qt
-  # install_qt creates the install at $PWD/Qt.
-  QT_CI_PACKAGES=qt.qt5.597.gcc_64,qt.qt5.597.qtwebengine PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt 5.9.7
+  # install-qt creates the install at $PWD/Qt.
+  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.gcc_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
   popd;
+  if [ ! -e ${QTDIR}/bin/qmake ]; then
+    echo "ERROR: qmake not found on the installation path." >&2
+    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
+    find ${HOME}/Qt -maxdepth 3
+    cat ${HOME}/Qt/InstallationLog.txt
+    cat ${HOME}/Qt/components.xml
+    exit 1
+  fi
 fi
-# note that qt-5.9.7.env created by install-qt is not cached!
+# note that qt-x.y.z.env created by install-qt is not cached!
 export PATH=${QTDIR}/bin:${PATH}
-unset -v QTDIR
+unset -v QT_VERSION QT_VERSION_SHORT QTDIR
 
 # prepare locale for test_encoding_latin1, requires locales package.
 sudo rm -rf /var/lib/apt/lists/* \
diff --git a/tools/travis_install_osx b/tools/travis_install_osx
--- a/tools/travis_install_osx
+++ b/tools/travis_install_osx
@@ -5,8 +5,11 @@
 # be used outside this script.
 #
 
-# our expectation is that qt-5.9.5-osx creates $QTDIR, $QTDIR/bin.
-QTDIR=${HOME}/Qt/5.9.5/clang_64
+QT_VERSION=${1:-5.12.0}
+QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')
+
+# our expectation is that install-qt-osx creates $QTDIR, $QTDIR/bin.
+QTDIR=${HOME}/Qt/${QT_VERSION}/clang_64
 
 if [ -d "${QTDIR}/bin" ]; then
   echo "Using cached Qt."
@@ -15,10 +18,18 @@ if [ -d "${QTDIR}/bin" ]; then
 else
   pushd ${HOME};
   rm -fr Qt
-  # qt-5.9.5-osx creates the install at $PWD/Qt.
-  QT_CI_PACKAGES=qt.595.clang_64,qt.595.qtwebengine PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} qt-5.9.5-osx;
+  # install-qt-osx creates the install at $PWD/Qt.
+  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.clang_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt-osx ${QT_VERSION}
   popd;
+  if [ ! -e ${QTDIR}/bin/qmake ]; then
+    echo "ERROR: qmake not found on the installation path." >&2
+    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
+    find ${HOME}/Qt -maxdepth 3
+    cat ${HOME}/Qt/InstallationLog.txt
+    cat ${HOME}/Qt/components.xml
+    exit 1
+  fi
 fi
-# note that qt-5.9.5-osx.env created by qt-5.9.5-osx is not cached!
+# note that qt-x.y.z.env created by install-qt-osx is not cached!
 export PATH=${QTDIR}/bin:${PATH}
-unset -v QTDIR
+unset -v QT_VERSION QT_VERSION_SHORT QTDIR
