Mac5120 (#283)
* add generic qt installer for osx.

add travis builds with osx and qt 5.9.7, 5.12.0
update qtci extract-qt-installer from upstream.
add some error detection and debug to travis_install_osx, travis_intall_linux_local.

* catch qtci/install-qt up with upstream.

* try harder with early extract-qt-installer bugs on osx.

* don't source travis qt install scripts.

* fix caching for travis.

* qt installer improvements

validate installs
add debug for failed installs

* update travis osx qt 5.12 build to 5.12.1.

diff --git a/tools/travis_install_osx b/tools/travis_install_osx
--- a/tools/travis_install_osx
+++ b/tools/travis_install_osx
@@ -1,24 +1,50 @@
 #!/bin/bash -ex
 #
 # This script is run on travis for the install stage of mac builds.
-# Note the script must be sourced if you want the modified PATH to
-# be used outside this script.
 #
 
-# our expectation is that qt-5.9.5-osx creates $QTDIR, $QTDIR/bin.
-QTDIR=${HOME}/Qt/5.9.5/clang_64
+#debug failed install
+function debug() {
+  cat ${CACHEDIR}/qt-${QT_VERSION}.env
+  find ${CACHEDIR}/Qt -maxdepth 3 -ls
+  cat ${CACHEDIR}/Qt/InstallationLog.txt
+  cat ${CACHEDIR}/Qt/components.xml
+  echo "$1" >&2
+  exit 1
+}
+
+# validate install
+function validate() {
+  (
+    set +e
+    source ${CACHEDIR}/qt-${QT_VERSION}.env
+    if [ "$(qmake -query QT_INSTALL_BINS)" != "${QTDIR}/bin" ]; then
+      debug "ERROR: unexpected Qt location."
+    fi
+    if [ "$(qmake -query QT_VERSION)" != "${QT_VERSION}" ]; then
+      debug "ERROR: wrong Qt version."
+    fi
+  )
+}
+
+QT_VERSION=${1:-5.12.0}
+QT_VERSION_SHORT=${QT_VERSION//./}
+
+# our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
+CACHEDIR=${HOME}/Cache
+QTDIR=${CACHEDIR}/Qt/${QT_VERSION}/clang_64
 
 if [ -d "${QTDIR}/bin" ]; then
   echo "Using cached Qt."
   echo "If you need to clear the cache see"
   echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
 else
-  pushd ${HOME};
-  rm -fr Qt
-  # qt-5.9.5-osx creates the install at $PWD/Qt.
-  QT_CI_PACKAGES=qt.595.clang_64,qt.595.qtwebengine PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} qt-5.9.5-osx;
-  popd;
+  rm -fr ${CACHEDIR}
+  mkdir -p ${CACHEDIR}
+  pushd ${CACHEDIR}
+  # install-qt creates the install at $PWD/Qt.
+  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.clang_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
+  popd
+  validate
+  rm ${CACHEDIR}/qt-opensource*.dmg
 fi
-# note that qt-5.9.5-osx.env created by qt-5.9.5-osx is not cached!
-export PATH=${QTDIR}/bin:${PATH}
-unset -v QTDIR
